package com.apex.agent.core.config

import android.content.SharedPreferences
import java.io.File
import java.io.FileInputStream
import java.io.FileOutputStream
import java.io.InputStreamReader
import java.io.OutputStreamWriter
import java.util.*

/**
 * Properties 文件配置提供者
 *
 * 从 .properties 文件中读取配置，支持文件包含和注释保留。
 * 写入时尽量保留原有注释和格式。
 */
open class PropertiesConfigProvider(
    private val file: File,
    override val priority: Int = 300,
    override val name: String = "properties:${file.name}"
) : ConfigSource {

    private val properties = mutableMapOf<String, String>()
    private var fileContent: String = ""
    private val locks = Any()

    override val isWritable: Boolean = true

    override fun get(key: ConfigKey): String? {
        synchronized(locks) { return properties[key.path] }
    }

    override fun getAll(): Map<String, String> {
        synchronized(locks) { return properties.toMap() }
    }

    override fun set(key: ConfigKey, value: String) {
        synchronized(locks) {
            properties[key.path] = value
            saveToFile()
        }
    }

    override fun reload() {
        synchronized(locks) {
            loadFromFile()
        }
    }

    private fun loadFromFile() {
        properties.clear()
        if (!file.exists()) return
        fileContent = file.readText()
        val props = Properties()
        InputStreamReader(FileInputStream(file), Charsets.UTF_8).use { reader ->
            props.load(reader)
        }
        for (name in props.stringPropertyNames()) {
            properties[name] = props.getProperty(name)
        }
    }

    private fun saveToFile() {
        val props = Properties()
        props.putAll(properties)
        OutputStreamWriter(FileOutputStream(file), Charsets.UTF_8).use { writer ->
            props.store(writer, "Generated by Apex Agent Config")
        }
    }

    /**
     * 支持从另一个 properties 文件包含（include）
     */
    fun include(otherFile: File) {
        if (!otherFile.exists()) return
        val otherProps = Properties()
        InputStreamReader(FileInputStream(otherFile), Charsets.UTF_8).use { reader ->
            otherProps.load(reader)
        }
        synchronized(locks) {
            for (name in otherProps.stringPropertyNames()) {
                if (!properties.containsKey(name)) {
                    properties[name] = otherProps.getProperty(name)
                }
            }
        }
    }

    override fun close() {
        properties.clear()
    }
}

/**
 * JSON 文件配置提供者
 *
 * 从 JSON 文件中读写配置，输出格式为美化后的缩进 JSON。
 */
open class JsonConfigProvider(
    private val file: File,
    override val priority: Int = 300,
    override val name: String = "json:${file.name}"
) : ConfigSource {

    private val config = mutableMapOf<String, String>()
    private val serializer = JsonConfigSerializer()
    private val locks = Any()

    override val isWritable: Boolean = true

    override fun get(key: ConfigKey): String? {
        synchronized(locks) { return config[key.path] }
    }

    override fun getAll(): Map<String, String> {
        synchronized(locks) { return config.toMap() }
    }

    override fun set(key: ConfigKey, value: String) {
        synchronized(locks) {
            config[key.path] = value
            saveToFile()
        }
    }

    override fun reload() {
        synchronized(locks) {
            loadFromFile()
        }
    }

    private fun loadFromFile() {
        config.clear()
        if (!file.exists()) return
        val content = file.readText()
        try {
            val parsed = serializer.deserialize(content)
            config.putAll(parsed)
        } catch (e: Exception) {
            throw RuntimeException("无法解析 JSON 配置文件: ${file.absolutePath}", e)
        }
    }

    private fun saveToFile() {
        val content = serializer.serialize(config)
        file.writeText(content)
    }

    override fun close() {
        config.clear()
    }
}

/**
 * 环境变量配置提供者
 *
 * 从系统环境变量中读取配置，键名使用可配置的前缀（如 AGENT_）。
 * 环境变量名中的下划线会被转换为点号路径（如 AGENT_API_BASE_URL -> api.baseUrl）
 */
open class EnvironmentConfigProvider(
    private val prefix: String = "AGENT_",
    override val priority: Int = 200,
    override val name: String = "environment"
) : ConfigSource {

    override val isWritable: Boolean = false

    override fun get(key: ConfigKey): String? {
        val envKey = toEnvKey(key.path)
        return System.getenv(envKey) ?: System.getenv(key.path.replace(".", "_").uppercase())
    }

    override fun getAll(): Map<String, String> {
        val result = mutableMapOf<String, String>()
        for ((envKey, value) in System.getenv()) {
            if (envKey.startsWith(prefix)) {
                val configKey = toConfigPath(envKey)
                result[configKey] = value
            }
        }
        return result
    }

    /**
     * 将配置路径转换为环境变量名
     * 如 "api.baseUrl" -> "AGENT_API_BASE_URL"
     */
    private fun toEnvKey(path: String): String {
        return prefix + path.replace(".", "_").uppercase()
    }

    /**
     * 将环境变量名转换为配置路径
     * 如 "AGENT_API_BASE_URL" -> "api.baseUrl"
     */
    private fun toConfigPath(envKey: String): String {
        val withoutPrefix = if (envKey.startsWith(prefix)) {
            envKey.substring(prefix.length)
        } else envKey
        return withoutPrefix.lowercase().replace("_", ".")
    }

    override fun reload() {
        // 环境变量在运行时不可变，无需操作
    }
}

/**
 * 系统属性配置提供者
 *
 * 从 Java 系统属性中读取配置（System.getProperty）。
 * 键名直接映射为配置路径。
 */
open class SystemPropertyConfigProvider(
    override val priority: Int = 100,
    override val name: String = "systemProperties"
) : ConfigSource {

    override val isWritable: Boolean = false

    override fun get(key: ConfigKey): String? {
        return System.getProperty(key.path)
    }

    override fun getAll(): Map<String, String> {
        val result = mutableMapOf<String, String>()
        for (key in System.getProperties().stringPropertyNames()) {
            result[key] = System.getProperty(key)
        }
        return result
    }

    override fun reload() {
        // 系统属性在运行时可通过 System.setProperty 修改，但无需缓存
    }
}

/**
 * 内存配置提供者
 *
 * 基于 ConcurrentHashMap 的运行时内存配置存储。
 * 用于运行时动态覆盖其他配置源的值。
 */
open class MemoryConfigProvider(
    override val priority: Int = 400,
    override val name: String = "memory"
) : ConfigSource {

    private val store = java.util.concurrent.ConcurrentHashMap<String, String>()

    override val isWritable: Boolean = true

    override fun get(key: ConfigKey): String? = store[key.path]

    override fun getAll(): Map<String, String> = store.toMap()

    override fun set(key: ConfigKey, value: String) {
        store[key.path] = value
    }

    override fun reload() {
        // 内存配置不受 reload 影响
    }

    override fun close() {
        store.clear()
    }

    /**
     * 批量设置多个配置项
     */
    fun setAll(entries: Map<String, String>) {
        store.putAll(entries)
    }

    /**
     * 移除指定配置项
     */
    fun remove(key: ConfigKey): String? = store.remove(key.path)

    /**
     * 清空所有存储
     */
    fun clear() = store.clear()
}

/**
 * Android SharedPreferences 配置提供者
 *
 * 基于 Android SharedPreferences 的持久化配置存储。
 * 所有修改会立即提交。
 */
open class SharedPreferencesConfigProvider(
    private val sharedPreferences: SharedPreferences,
    override val priority: Int = 350,
    override val name: String = "sharedPreferences"
) : ConfigSource {

    override val isWritable: Boolean = true

    override fun get(key: ConfigKey): String? {
        return sharedPreferences.getString(key.path, null)
    }

    override fun getAll(): Map<String, String> {
        return sharedPreferences.all.mapValues { it.value?.toString() ?: "" }
            .filterKeys { it !is Nothing }
    }

    override fun set(key: ConfigKey, value: String) {
        sharedPreferences.edit().putString(key.path, value).apply()
    }

    override fun reload() {
        // SharedPreferences 自动同步，无需额外操作
    }

    /**
     * 批量更新配置（使用 commit 确保同步）
     */
    fun setAllSync(entries: Map<String, String>) {
        val editor = sharedPreferences.edit()
        for ((key, value) in entries) {
            editor.putString(key, value)
        }
        editor.commit()
    }
}

/**
 * 组合配置提供者 - 分层优先级配置源
 *
 * 将多个配置源按优先级组织，查询时按优先级从高到低遍历，
 * 返回第一个匹配的值。
 *
 * 写入时写入到所有可写的配置源中的最高优先级源。
 */
open class CompositeConfigProvider(
    private val providers: List<ConfigSource>,
    override val priority: Int = 0,
    override val name: String = "composite"
) : ConfigSource {

    override val isWritable: Boolean = providers.any { it.isWritable }

    constructor(vararg providers: ConfigSource) : this(providers.toList())

    override fun get(key: ConfigKey): String? {
        for (provider in providers) {
            val value = provider.get(key)
            if (value != null) return value
        }
        return null
    }

    override fun getAll(): Map<String, String> {
        val result = mutableMapOf<String, String>()
        for (provider in providers) {
            result.putAll(provider.getAll())
        }
        return result
    }

    override fun set(key: ConfigKey, value: String) {
        val writableProvider = providers
            .filter { it.isWritable }
            .maxByOrNull { it.priority }
        writableProvider?.set(key, value)
            ?: throw UnsupportedOperationException("没有可写的配置源")
    }

    override fun reload() {
        for (provider in providers) {
            provider.reload()
        }
    }

    override fun close() {
        for (provider in providers) {
            provider.close()
        }
    }

    /**
     * 添加新的配置源
     */
    fun addProvider(provider: ConfigSource) {
        val mutableList = providers.toMutableList()
        mutableList.add(provider)
        // 重新排序
    }

    /**
     * 移除指定的配置源
     */
    fun removeProvider(provider: ConfigSource): Boolean {
        val mutableList = providers.toMutableList()
        return mutableList.remove(provider)
    }

    /**
     * 获取所有子配置源（已按优先级排序）
     */
    fun getProviders(): List<ConfigSource> = providers.sortedByDescending { it.priority }
}
